In [ ]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

In [ ]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [2]:
import sys
import pandas as pd
import pandas_profiling as pds
import numpy as np
from pandas_profiling import ProfileReport

# Read the CSV and Perform Basic Data Cleaning

In [3]:
df = pd.read_csv("../data/raw/exoplanet_data.csv")
# Drop the null columns where all values are null
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

In [4]:
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6991 entries, 0 to 6990
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   koi_disposition    6991 non-null   object 
 1   koi_fpflag_nt      6991 non-null   int64  
 2   koi_fpflag_ss      6991 non-null   int64  
 3   koi_fpflag_co      6991 non-null   int64  
 4   koi_fpflag_ec      6991 non-null   int64  
 5   koi_period         6991 non-null   float64
 6   koi_period_err1    6991 non-null   float64
 7   koi_period_err2    6991 non-null   float64
 8   koi_time0bk        6991 non-null   float64
 9   koi_time0bk_err1   6991 non-null   float64
 10  koi_time0bk_err2   6991 non-null   float64
 11  koi_impact         6991 non-null   float64
 12  koi_impact_err1    6991 non-null   float64
 13  koi_impact_err2    6991 non-null   float64
 14  koi_duration       6991 non-null   float64
 15  koi_duration_err1  6991 non-null   float64
 16  koi_duration_err2  6991 

In [6]:
# profile = ProfileReport(df, title="Pandas Profiling Report")
# profile
# Select your features (columns)
# Set features. This will also be used as your x values.
# selected_features = df[['names', 'of', 'selected', 'features', 'here']]

In [7]:
selected_features = df[['koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec','koi_period','koi_time0bk','koi_impact','koi_duration','koi_duration','koi_depth','koi_prad','koi_teq','koi_insol','koi_model_snr','koi_tce_plnt_num','koi_steff','koi_slogg','koi_srad','ra','dec','koi_kepmag','koi_disposition']]
selected_features.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0              0              0              0              0   54.418383   
1              0              1              0              0   19.899140   
2              0              1              0              0    1.736952   
3              0              0              0              0    2.525592   
4              0              0              0              0    4.134435   

   koi_time0bk  koi_impact  koi_duration  koi_duration  koi_depth  ...  \
0   162.513840       0.586       4.50700       4.50700      874.8  ...   
1   175.850252       0.969       1.78220       1.78220    10829.0  ...   
2   170.307565       1.276       2.40641       2.40641     8079.2  ...   
3   171.595550       0.701       1.65450       1.65450      603.3  ...   
4   172.979370       0.762       3.14020       3.14020      686.0  ...   

   koi_insol  koi_model_snr  koi_tce_plnt_num  koi_steff  koi_slogg  koi_srad  \
0       9.11           25.8                 2       5455      4.467     0.927   
1      39.30           76.3                 1       5853      4.544     0.868   
2     891.96          505.6                 1       5805      4.564     0.791   
3     926.16           40.9                 1       6031      4.438     1.046   
4     427.65           40.2                 2       6046      4.486     0.972   

          ra        dec  koi_kepmag  koi_disposition  
0  291.93423  48.141651      15.347        CONFIRMED  
1  297.00482  48.134129      15.436   FALSE POSITIVE  
2  285.53461  48.285210      15.597   FALSE POSITIVE  
3  288.75488  48.226200      15.509        CONFIRMED  
4  296.28613  48.224670      15.714        CONFIRMED  

[5 rows x 22 columns]

In [8]:
confirmed_features = selected_features.loc[selected_features["koi_disposition"]=="CANDIDATE" && selected_features["koi_disposition"]=="CANDIDATE"]
confirmed_features.tail()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
6979              0              0              0              0    4.736816   
6980              0              0              0              0  130.235324   
6984              0              0              0              0    8.870416   
6985              0              0              0              0   47.109631   
6988              0              0              0              0    1.739849   

      koi_time0bk  koi_impact  koi_duration  koi_duration  koi_depth  ...  \
6979   131.787600       0.218        2.8400        2.8400       35.3  ...   
6980   218.271900       0.075        5.6780        5.6780      750.1  ...   
6984   137.481093       1.206        1.2864        1.2864      873.1  ...   
6985   144.131720       1.230        5.7410        5.7410      752.2  ...   
6988   133.001270       0.043        3.1140        3.1140       48.5  ...   

      koi_insol  koi_model_snr  koi_tce_plnt_num  koi_steff  koi_slogg  \
6979     395.05            6.9                 1       6088      4.456   
6980       2.86            9.7                 1       5616      4.529   
6984     414.26           43.8                 1       6022      4.027   
6985      75.40           35.1                 1       5258      3.597   
6988    1585.81           10.6                 1       6119      4.444   

      koi_srad         ra        dec  koi_kepmag  koi_disposition  
6979     1.011  289.20331  44.505138      13.922        CANDIDATE  
6980     0.903  289.57452  44.519939      15.991        CANDIDATE  
6984     1.514  290.14914  50.239178      13.579        CANDIDATE  
6985     2.780  296.15601  44.920090      13.731        CANDIDATE  
6988     1.031  286.50937  47.163219      14.757        CANDIDATE  

[5 rows x 22 columns]

# Create a Train Test Split

Use `koi_disposition` for the y values

In [9]:
data = selected_features.values
X = data[:, 0:20]
y = selected_features["koi_disposition"].values.reshape(-1, 1)
print(X.shape, y.shape)

(6991, 20) (6991, 1)


In [10]:
from sklearn.preprocessing import LabelEncoder
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)
encoded_y

C:\Users\Donley\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([1, 2, 2, ..., 0, 2, 2])

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=1)

In [12]:
# X_train.head()

In [13]:
# for label, original_class in zip(encoded_y, y):
#     print('Original Class: ' + str(original_class))
#     print('Encoded Label: ' + str(label))
#     print('-' * 12)



# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [17]:
from tensorflow.keras.utils import to_categorical

# Step 2: # One-hot encoding to categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_train_categorical


array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [18]:
from sklearn.preprocessing import MinMaxScaler
# Scale your data
# build the scaler model
scaler = MinMaxScaler()
# fit using the train set
X_scaler = scaler.fit(X_train)
# transform the train & test
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [19]:
 X_test_scaled

array([[0.        , 0.        , 0.        , ..., 0.00361304, 0.55368875,
        0.10624782],
       [1.        , 0.        , 0.        , ..., 0.00469695, 0.56376692,
        0.27533664],
       [1.        , 0.        , 0.        , ..., 0.00546958, 0.55054376,
        0.8357821 ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.00399102, 0.46921294,
        0.28946484],
       [0.        , 1.        , 0.        , ..., 0.00909374, 0.78806129,
        0.81638257],
       [0.        , 0.        , 0.        , ..., 0.01188412, 0.31299327,
        0.22798481]])

In [20]:
# Verify maximum value of all features
X_trained_max = X_train_scaled.max(axis=0)
X_trained_max 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [21]:
# Manually normalise without using scikit-learn
X_manual_scaled = (X_train - X_train.min(axis=0)) / (X_train.max(axis=0) - X_train.min(axis=0))
# Verify manually VS scikit-learn estimation
# print(np.allclose(X_scaled, X_manual_scaled))
np.isfinite(X_train_scaled, X_train_scaled)
# True

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [22]:
# first, create a normal neural network with 3 inputs, 20 hidden nodes, and 3 outputs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

In [23]:
from tensorflow.keras.layers import Dense
# number_inputs = 6
number_hidden_nodes = 20
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=20))

In [24]:
number_classes = 3
model.add(Dense(units=number_classes, activation='softmax'))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                420       
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 63        
Total params: 483
Trainable params: 483
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the Model



In [27]:
# Fit the model to the training data
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Epoch 1/1000
164/164 - 0s - loss: 1.0563 - accuracy: 0.4650
Epoch 2/1000
164/164 - 0s - loss: 1.0443 - accuracy: 0.4949
Epoch 3/1000
164/164 - 0s - loss: 1.0436 - accuracy: 0.4949
Epoch 4/1000
164/164 - 0s - loss: 1.0442 - accuracy: 0.4949
Epoch 5/1000
164/164 - 0s - loss: 1.0440 - accuracy: 0.4949
Epoch 6/1000
164/164 - 0s - loss: 1.0437 - accuracy: 0.4949
Epoch 7/1000
164/164 - 0s - loss: 1.0439 - accuracy: 0.4949
Epoch 8/1000
164/164 - 0s - loss: 1.0443 - accuracy: 0.4949
Epoch 9/1000
164/164 - 0s - loss: 1.0440 - accuracy: 0.4949
Epoch 10/1000
164/164 - 0s - loss: 1.0434 - accuracy: 0.4949
Epoch 11/1000
164/164 - 0s - loss: 1.0442 - accuracy: 0.4949
Epoch 12/1000
164/164 - 0s - loss: 1.0438 - accuracy: 0.4949
Epoch 13/1000
164/164 - 0s - loss: 1.0439 - accuracy: 0.4949
Epoch 14/1000
164/164 - 0s - loss: 1.0443 - accuracy: 0.4949
Epoch 15/1000
164/164 - 0s - loss: 1.0438 - accuracy: 0.4949
Epoch 16/1000
164/164 - 0s - loss: 1.0440 - accuracy: 0.4949
Epoch 17/1000
164/164 - 0s - loss

In [ ]:
model_loss, model_accuracy = model.evaluate(
    X_train_scaled, y_train_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
import matplotlib.pyplot as plt

plt.plot(range(model.epochs), model.eval_['Accuracy'], 
         label='Training')
plt.plot(range(model.epochs), nn.eval_['Loss'], 
         label='Validation', linestyle='--')
plt.ylabel('Accuracy')
plt.xlabel('Epochs')
plt.legend(loc='lower right')
# plt.savefig('01.png', dpi=300)
plt.show()

In [ ]:
print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# Create the GridSearchCV model

In [ ]:
# Train the model with GridSearch

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)